### ISSUE TITLE
41_insert_sort 插入排序算法 可能不是很对

### ISSUE THREAD

**Issue by taojy123** [oldman1991/testdemo#1]
你好，我看了你的插入排序算法
其中26行，list_a[j - 1], list_a[j] = list_a[j], list_a[j - 1]
这里交换了两个数的位置，这样写其实就不太好了。
为什么插入排序比冒泡排序更快一些，主要就是因为冒泡排序每一轮都要进行多次的交换，而插入排序每一轮是多次的赋值+一次的交换。
所以我觉得正确的做法应该是先记录下 list_a[i] 的值保存到比如 value 变量中，然后 list_a[j - 1], list_a[j] = list_a[j], list_a[j - 1] 这里可以直接写成 list_a[j] = list_a[j-1]，最后在 list_a[j] = value。

**Comment by lipeng1991** [comment]
你说的很对，是一个优化的地方。感谢
